### ISSUE TITLE
Veja esse tutorial

### ISSUE THREAD

**Issue by ghost** [ykwy404/Chess#1]
>[~~tutorial.zip~~](https://github.com/ykwy404/Chess/files/10146427/tutorial.zip)
versão **aprimorada** do antigo [tutorial](https://github.com/kwy404/Chess/files/10891703/tutorial.zip)

É um tutorial sobre como programar um jogo de xadrez em javascript.

Acho que você precisa dar uma olhada

**Comment by kwy404** [comment]
Beleza, valeu.
Vou dar uma olhada
